name: chat_gpt_sdk
description: create chat bot and other bot with ChatGPT SDK Support GPT-4 , 3.5 and SSE Generate Prompt (Stream)
version: 2.2.5
homepage: https://www.facebook.com/REDEVRX
repository: https://github.com/redevRx/Flutter-ChatGPT

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dio:
  http_parser:

dev_dependencies:
  mockito: 
  build_runner: 
  coverage: 
  dart_code_metrics:
  test: 
